4_20221028_4.out: ../utilities/basics.o 4_20221028_4.o
	clang ../utilities/basics.o 4_20221028_4.o -o 4_20221028_4.out
../utilities/basics.o: ../utilities/basics.h ../utilities/basics.c
	clang -c ../utilities/basics.c -o ../utilities/basics.o
4_20221028_4.o: ../utilities/basics.h 4_20221028_4.c
	clang -c 4_20221028_4.c -o 4_20221028_4.o